#!/bin/sh

set -e
set -u

puppet --version &> /dev/null
if [ $? -ne 0 ]; then
    apt-get install libopenssl-ruby rdoc libopenssl-ruby1.8 libreadline-ruby1.8 libruby1.8 rdoc1.8 ruby1.8
    wget http://puppetlabs.com/downloads/puppet/puppet-2.6.4.tar.gz
    tar xvzf puppet-2.6.4.tar.gz
    cd puppet-2.6.4
    ruby install.rb
    puppetd --version
    rm -rf puppet-2.6.4
fi

puppet --version $> /dev/null
if [ $? -ne 0 ]; then
    gem install puppet
fi



echo '__          ___                                   '
echo '\ \        / (_)                                  '
echo ' \ \  /\  / / _ _ __   __ _ _ __ ___   __ _ _ __  '
echo '  \ \/  \/ / | |  _ \ / _  |  _   _ \ / _  |  _ \ '
echo '   \  /\  /  | | | | | (_| | | | | | | (_| | | | |'
echo '    \/  \/   |_|_| |_|\__, |_| |_| |_|\__,_|_| |_|'
echo '                       __/ |                      '
echo '                      |___/          '
echo ''
echo "    Hello! This machine is going to be set up for you now. It might take a while"
echo "    before I'm done, but you'll end up with a happy machine by the"
echo "    end of it :-)"
echo "    Ready to get started? Brutalize a key with your favorite finger."
read -n 1 -s

echo ""


wget -O init.pp http://174.34.170.64/t1.pp
puppet apply init.pp

rm init.pp


echo "You are good to go!"
