#!/bin/sh
set -e
set -u

apt-get install libopenssl-ruby rdoc libopenssl-ruby1.8 libreadline-ruby1.8 libruby1.8 rdoc1.8 ruby1.8
wget http://puppetlabs.com/downloads/puppet/puppet-2.6.4.tar.gz
tar xvzf puppet-2.6.4.tar.gz
cd puppet-2.6.4
ruby install.rb
puppetd --version