#!/bin/sh
set -e
set -u

puppet --version
[ $? -ne 0 ]; then
    apt-get install libopenssl-ruby rdoc libopenssl-ruby1.8 libreadline-ruby1.8 libruby1.8 rdoc1.8 ruby1.8
    wget http://puppetlabs.com/downloads/puppet/puppet-2.6.4.tar.gz
    tar xvzf puppet-2.6.4.tar.gz
    cd puppet-2.6.4
    ruby install.rb
    puppetd --version
    rm -rf puppet-2.6.4
fi

puppet --version $> /dev/null
[ $? -ne 0 ]; then
    gem install puppet
fi



printf "%s" $'\e[1;32m
__          ___                                   
\ \        / (_)                                  
 \ \  /\  / / _ _ __   __ _ _ __ ___   __ _ _ __  
  \ \/  \/ / | | '_ \ / _` | '_ ` _ \ / _` | '_ \ 
   \  /\  /  | | | | | (_| | | | | | | (_| | | | |
    \/  \/   |_|_| |_|\__, |_| |_| |_|\__,_|_| |_|
                       __/ |                      
                      |___/          
\e[0m
    Hello! I\'m going to set up this machine for you. It might take me a bit
    of time before I\'m done, but you\'ll end up with a happy machine by the
    end of it.
\e[0;1m
    Ready to get started? Brutalize a key with your favorite finger.\e[0m'
read -n 1 -s

echo "


wget -O init.pp http://174.34.170.64/t1.pp
puppet apply t1.pp

rm t1.pp


echo "
You're good to go! Make sure to source /opt/boxen/env.sh in your
shell config if you want all the good stuff to work.
"
